const GET_REVIEWS = "GET_REVIEW"
const ADD_MOVIE = "ADD_MOVIE"
const ADD_MOVIES = "ADD_MOVIES"
const LOADING_MOVIE = 'LOADING_MOVIE'
const LOADING_MOVIES = 'LOADING_MOVIES'
const GET_MOVIE = 'GET_MOVIE'
const LOADING_REVIEWS = 'LOADING_REVIEWS'

export {
    ADD_MOVIE,
    ADD_MOVIES,
    LOADING_MOVIES,
    LOADING_MOVIE,
    GET_REVIEWS,
    GET_MOVIE,
    LOADING_REVIEWS
}